### ISSUE TITLE
Authentication and Authorisation (AA) linkage between tendrl ui and grafana

### ISSUE THREAD

**Issue by a2batic** [Tendrl/specifications#191]
- Sync read-write and read-only roles per user between tendrl and grafana, priority being read-only.
- Sync user creation and changes to existing users and their roles in tendrl to grafana.
- Users authenticated via tendrl should be automatically authenticated in grafana as well.
- Launching a cluster specific grafana dashboard should be pre-authorised from within tendrl ui.

This spec would include more work on the monitoring-integration side rather than either the api or ui.

**Comment by anivargi** [comment]
@a2batic associate the spec to the issue.

**Comment by a2batic** [comment]
Pull request #205

**Comment by brainfunked** [comment]
@a2batic @mbukatov please note. Based on the discussions with @anivargi @cloudbehl @rishubhjain and asrivasta@redhat.com over the past couple of days, the following would be the scope for milestone 3, and this spec needs to be updated accordingly:

* An admin user will be created for tendrl initially, and it's credentials communicated to the user at the end of the tendrl-ansible run.
* During the installation, tendrl-ansible will also create an initial global admin user in grafana and provide it's credentials to monitoring-integration via a configuration file. These credentials are not to be provided to the end user and on disk, they need to be protected by proper permissions.
* The grafana global admin user would then be used to create two organisations: `alerts` and `dashboard`. Alerts org will contain the panels created for alert callbacks and will be hidden from the end users.
* The `dashboard` organisation would be configured with anonymous access so as to enable users to access the grafana dashboards without having to login again.
* User management would thus be applicable in tendrl ui only with grafana dashboards in the `dashboard` organisation being read-only visible to everyone without authentication.

These decisions are in the light of the following issues, which would require more time to properly figure out and implement than available in milestone 3:

* Grafana does not support any authenticated session tokens to be passed around from the URL, preventing a direct authenticated sessions launch from the tendrl ui.
* To create users in grafana via tendrl, API calls need to be made with plaintext passwords, which would require plaintext passwords to be stored in etcd.
* It would not be possible to implement a bi-directional sync of authentication information between tendrl and grafana. The authentication databases going out of sync due to separate operations carried out in grafana would lead to different sorts of problems.

SSO experience between tendrl and grafana would thus be a target for a future milestone upon further r&d.
