### ISSUE TITLE
Merge node namespace with Cluster namespace

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/specifications#236]
With the changes lined up for https://github.com/Tendrl/specifications/issues/213

tendrl-node-agent can purely rely on Cluster.is_managed to group cluster nodes under the "clusters/<integration_id>" namespace.

This issue to capture all known and unknowns for this merge

**Comment by anivargi** [comment]
Here are my thoughts:
- Nodes already part of a clusters (imported/detected) always reside under `/clusters/:cluster_id/nodes`. 
- Nodes which are not part of any cluster which can be used for create/expand will be under `/nodes`

To manage cases where we need a list of host across all clusters, we could add a index like node_id : cluster_id, but I don't see the use case for showing this view.

**Comment by r0h4n** [comment]
@anmolbabu how does @anivargi comment affect monitoring collectors?

**Comment by brainfunked** [comment]
@r0h4n which milestone is this aimed at?

**Comment by anmolbabu** [comment]
@r0h4n This doesn't affect me in any way because my atom is invoked automatically as part of import cluster flow.. As long as NS.node_context is intact I am not really affected by this change..
Also, if we are going with above decision is it possible to add a way to indicate the exact peer name as gluster knows in NS.node_context ?? Currently there is a field called fqdn which is just socket.gethostname but in case of nodes with multiple ips we are only interested in details pertaining to cluster network so there this would be helpful.. This is not related to this issue but I just wanted to bring this up

**Comment by r0h4n** [comment]
@anmolbabu So to summarize

- This issue does not affect collectd plugins because all of them use NS.node_context


Please file an issue on commons for fqdn change right away

**Comment by anmolbabu** [comment]
@r0h4n Done https://github.com/Tendrl/commons/issues/687
